AG-5663-Send-All-Tenants-From-Metrics-Server
wtag/blabber pull request #29
Opened 2021-03-28 07:41 UTC by sas-wtag

2021-03-29 12:56 UTC, luxflux requested changes
Please also regenerate the Ruby libraries.

2021-03-29 14:10 UTC, luxflux approved these changes

2021-03-30 06:21 UTC, hok-wtag requested changes

2021-03-30 06:21 UTC, hok-wtag commented on nodejs/agent-platform/userRelationships_grpc_pb.js
> +  return Buffer.from(arg.serializeBinary());
we dont need to touch anything of agent-platform, this update has nothing to do with agent

2021-03-30 06:21 UTC, hok-wtag commented on nodejs/chat-backend/chat_grpc_pb.js
> +  return Buffer.from(arg.serializeBinary());
i am sorry but i think the old syntax is right. though auto generated code is giving us new syntax but it does not work. so we can revert them and keep the old syntax. `new Buffer...`

2021-03-30 06:22 UTC, luxflux commented on nodejs/chat-backend/chat_grpc_pb.js
> +  return Buffer.from(arg.serializeBinary());
@hok-wtag why doesn't it work? Do we need to update grpc in chat-server maybe?

2021-03-30 06:23 UTC, luxflux commented on nodejs/agent-platform/userRelationships_grpc_pb.js
> +  return Buffer.from(arg.serializeBinary());
IMHO, we should always regenerate all the code. Otherwise we're reverting some parts and then have inconsistencies if someone forgets to revert these specific parts...

2021-03-31 06:56 UTC, sas-wtag commented on nodejs/chat-backend/chat_grpc_pb.js
> +  return Buffer.from(arg.serializeBinary());
@hok-wtag bhaiya i think there were inconsistencies with the older version of grpc tools. Atleast the new syntax now doesnt seem to hamper chat functionalities. Also writing in older syntax gives a deprecation error as below 
C.c = @luxflux 

gif:  https://recordit.co/Mbl4rDcZHf

2021-03-31 10:52 UTC, hok-wtag commented on nodejs/chat-backend/chat_grpc_pb.js
> +  return Buffer.from(arg.serializeBinary());
@luxflux , last time we had to track down and downgrade grpc as their latest version is not working for us. its auto generated code does not work at all but I don't know they fixed it yet or not. so may be @sas-wtag can give it a try

2021-03-31 10:53 UTC, hok-wtag commented on nodejs/agent-platform/userRelationships_grpc_pb.js
> +  return Buffer.from(arg.serializeBinary());
:( ya I wish their auto generated code works out of the box. if it does please feel free to move on but last time I checked it didn't worked. so @sas-wtag you can try with the auto generated code and check through that everything working.

2021-03-31 12:14 UTC, kup-wtag approved these changes

2021-04-01 02:53 UTC, hok-wtag approved these changes

2021-04-15 09:06 UTC, merged