AG-3258-Chat-Notification-Escalation
wtag/blabber pull request #30
Opened 2021-04-19 10:56 UTC by sas-wtag

2021-04-19 14:06 UTC, luxflux requested changes

2021-04-19 14:06 UTC, luxflux commented on proto-libs/agent-platform/userRelationships.proto
> +}
I think it'd be good to not just respond with an `Empty` response, I think it'd be great to respond with a success/failure:
```suggestion
message SendEmailResponse {
  bool success = 1;
}
```

2021-04-26 16:38 UTC, sas-wtag commented on proto-libs/agent-platform/userRelationships.proto
> +}
done

2021-04-26 16:59 UTC, luxflux requested changes

2021-04-26 16:59 UTC, luxflux commented on proto-libs/chat-backend/chat.proto
> +  rpc MessageSeenStatus(MessageSeenStatusRequest) returns (MessageSeenStatusResponse) {}
These changes shouldn't be in here, should they?

2021-04-26 16:59 UTC, luxflux commented on proto-libs/agent-platform/userRelationships.proto
> +message Empty {
We don't need this one anymore, do we?

2021-04-26 16:59 UTC, luxflux commented on proto-libs/agent-platform/userRelationships.proto
>  }
I think we should create a new service for this as `SendEmail` isn't really related to `UserRelationships`:
```suggestion
}

service Email {
  rpc Send(SendEmailRequest) returns (SendEmailResponse) {}
}
```

Not quite sure what this means on Agent side, though.

2021-04-26 17:12 UTC, luxflux commented on proto-libs/chat-backend/chat.proto
> +  string status = 1;
Not sure if we should call it `seen` and use a boolean instead?
```suggestion
  bool seen = 1;
```

2021-04-27 10:57 UTC, sas-wtag commented on proto-libs/agent-platform/userRelationships.proto
> +message Empty {
It has been removed !

2021-04-27 11:07 UTC, sas-wtag commented on proto-libs/chat-backend/chat.proto
> +  string status = 1;
done

2021-04-27 12:20 UTC, sas-wtag commented on proto-libs/agent-platform/userRelationships.proto
>  }
added

2021-04-27 15:07 UTC, luxflux requested changes

2021-04-27 15:07 UTC, luxflux commented on proto-libs/chat-backend/chat.proto
> +  bool isCustomer = 2;
I think you'd want to use something like this here (related to my other comment in the chat-server):
```suggestion
  int64 messageId = 1;
  Model.User user = 2;
```

2021-04-27 15:07 UTC, luxflux commented on proto-libs/agent-platform/userRelationships.proto
> +}
This is now somehow included in the user relation ship files. Could you introduce a new `email.proto` file to handle it?

2021-04-27 15:07 UTC, luxflux commented on proto-libs/agent-platform/userRelationships.proto
> +service SendEmail {
Let's name the service less specific so we can add more functionality around email later on:
```suggestion
service Email {
```

2021-05-02 10:36 UTC, sas-wtag commented on proto-libs/chat-backend/chat.proto
> +  bool isCustomer = 2;
done

2021-05-02 12:12 UTC, sas-wtag commented on proto-libs/agent-platform/userRelationships.proto
> +}
done

2021-05-02 12:12 UTC, sas-wtag commented on proto-libs/agent-platform/userRelationships.proto
> +service SendEmail {
done

2021-05-03 09:29 UTC, luxflux approved these changes
Please also update the build commands https://github.com/wtag/blabber/blob/master/package.json#L9-L10

2021-05-06 11:35 UTC, kup-wtag approved these changes

2021-05-10 06:48 UTC, mal-wtag approved these changes

2021-06-01 15:41 UTC, merged