AG-4088-Chat-Configure-Escalation-Period
wtag/blabber pull request #31
Opened 2021-05-06 09:13 UTC by sas-wtag

2021-05-10 09:47 UTC, sas-wtag commented on proto-libs/agent-platform/userRelationships.proto
> +  rpc RetrieveChatConfigurations(Model.User) returns (ChatConfigurations) {}
added a new proto file

2021-05-10 12:27 UTC, luxflux requested changes

2021-05-10 12:27 UTC, luxflux commented on proto-libs/agent-platform/userPreferences.proto
> +}
```suggestion
}
```

2021-05-10 12:27 UTC, luxflux commented on proto-libs/agent-platform/userPreferences.proto
> +    int64 notificationEscalationDelayInSeconds = 1;
Please check the indention, I think it should only be two spaces.

2021-05-10 12:27 UTC, luxflux commented on proto-libs/agent-platform/userPreferences.proto
> +    rpc RetrieveChatConfigurations(Model.User) returns (ChatConfigurations) {}
```suggestion
    rpc RetrieveChatPreferences(Model.User) returns (ChatConfigurations) {}
```

2021-05-10 12:27 UTC, luxflux commented on proto-libs/agent-platform/userPreferences.proto
> +message ChatConfigurations {
I'd call it preferences:
* A configuration is something more fundamental than a preference
* In the UI it's called preference as well - less confusion

```suggestion
message ChatPreferences {
```

2021-05-11 06:34 UTC, sas-wtag commented on proto-libs/agent-platform/userPreferences.proto
> +    int64 notificationEscalationDelayInSeconds = 1;
done

2021-05-11 06:34 UTC, sas-wtag commented on proto-libs/agent-platform/userPreferences.proto
> +    rpc RetrieveChatConfigurations(Model.User) returns (ChatConfigurations) {}
done

2021-05-11 06:34 UTC, sas-wtag commented on proto-libs/agent-platform/userPreferences.proto
> +message ChatConfigurations {
done

2021-05-11 10:07 UTC, luxflux requested changes

2021-05-11 10:25 UTC, sas-wtag commented on index.js
> +  userPreferencesService.ChatConfigurations;
done

2021-05-11 14:25 UTC, mal-wtag approved these changes

2021-06-07 07:25 UTC, merged